/*==============================================================================
	Choke
	
The little brother of Jitterskull was born a malformed giant, and was often a
target for picking on. His diminutive stature and lopsided body often made him
an outcast, and Choke struggled very hard to be liked. Unable to take it anymore,
Choke committed suicide, with his bigger brother burying him. When it was his
bigger brother's time to pass on, he requested to be buried next to Choke's side.

Even the Yurei hadn't wanted him - an accidental resurrection bring both Jitter's
head and Choke's to unlife, but she took them both under her arms as mindless
servants to wreak havoc upon humanity.

Choke is the fastest ghoul around, constantly on the move which renders him
partially invisible. Only when still is he fully revealed. He's much squishier
than his boney brother, but he also presents a serious hazard to those with
explosives.

He can also puke up his last meal as a dangerous ball of gore. The longer he 
charges it, the bigger it gets, including blast radius.

But he's vulnerable to stunlocking. Rapid fire weapons are best.

Recommended Weapon: Plasma Rifle or Chaingun
==============================================================================*/

class GS_Choke : GS_GhoulBase
{
	const thres = int.max - 1;
	Default
	{
		
		+EXTREMEDEATH
		GS_GhoulBase.PainDelay 15;
		GS_GhoulBase.DmgThreshold thres;
		Height 60;
		Radius 20;
		Speed 30;
		Health 700;
		MaxStepHeight 48;
		SeeSound "Choke/Taunt";
		ActiveSound "Choke/Chase";
		PainSound "Choke/Pain";
		DeathSound "Choke/Death";
		Species "GS_Choke";
		Tag "Choke";
	//	DamageFactor "Sjas", 0.4;
	//	DamageFactor "Jitter", 0.3;
	}
	
	
	/*
	Choke/Chase
	Choke/Melee
	Choke/Gargle
	Choke/Spit
	Choke/Taunt
	Choke/Interrupt
	Choke/Pain
	Choke/Death
	*/	
	
	
	States
	{
	Spawn:
		G004 C 8 A_Look();
		Loop;
	See:
		---- A 0 PlaySeeSound();
	Chasing:
		G004 AB 1 ChokeChase();
		Loop;
	Melee:
		G004 CD 2;
		G004 E 2 Bite();
		Goto Chasing;
	Missile:
		/*
		#### C 10 
		{
			A_StartSound("Choke/Gargle", 20, CHANF_OVERLAP);
		//	DmgThreshold = 50;
		}
		#### D 10;
		#### E 12 { bar = 0; }
		#### F 15;
		*/
		#### C 8 Jiggle(1);
		---- A 0 
		{
			bar = 0; 
			return A_Jump(256, "Barrage", "Single");//, "Huge");
		}
	Barrage:
		#### D 3 Spit(1);
		#### C 3 ;
		---- A 0 A_JumpIf(++bar < 5, "Barrage");
		---- A 0 Jiggle(1);
		Goto MislEnd;
	Single:
		#### D 10 Spit(2);
		#### C 4 Jiggle(1);
		Goto MislEnd;
	Huge:
		#### F 55 Jiggle(1);
		#### D 8 Spit(3);
		#### C 5 Jiggle(1);
		Goto MislEnd;
	MislEnd:
		---- A 0
		{
		//	DmgThreshold = int.max - 1;
		}
		Goto Chasing;
	Pain:
		#### F 3;
		#### F 5
		{
			
			A_StartSound("Choke/Interrupt", 5, CHANF_OVERLAP);
		}
		Goto Chasing;
	Death:
		G004 F 0 ChokeDeath();
		G004 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 ChokeBoom();
		G004 F 0 ChokeBoom(true);
		G004 GHIJ 3;
		Stop;
	}
	
	private int bar;
	
	private void Spit(int type)
	{
		Class<Actor> cls = null;
		Switch(type)
		{
			Default:	return;
			Case 1:	cls = "GS_ChokeBallLil";	break;
			Case 2:	cls = "GS_ChokeBallMed";	break;
		//	Case 3:	cls = "GS_ChokeBallBig";	break;
		}
		A_StartSound("Choke/Spit", 6, CHANF_OVERLAP);
		let mo = A_SpawnProjectile(cls, 24);
		if (mo)
		{
			if (cls == "GS_ChokeBallLil")
			{
				if (Target)
				{
					// Don't factor portals into this since it'll make the
					// shotgun spray weird.
					double ofs = 20.0;
					double ofr = Max(Target.Radius, ofs);
					double ofh = Max(Target.height, ofs);
					Vector3 v1 = Target.Pos - (ofr, ofr, 0);
					Vector3 v2 = Target.Pos + (ofr, ofr, ofh);
					
					Vector3 res = (
						frandom[rng](v1.x, v2.x),
						frandom[rng](v1.y, v2.y),
						frandom[rng](v1.z, v2.z)
						);
					[mo.Angle, mo.Pitch] = GS_Global.GetVectorAngles(mo.pos, res);
					mo.Vel3DFromAngle(mo.speed, mo.angle, mo.pitch);
				}
			}
		}
	}
	
	override int DoSpecialDamage(Actor tar, int dmg, Name type, int flags, double angle)
	{
		if (dmg > 0 && tar && tar != self && !tar.bKILLED && type == 'Melee')
		{
			GiveBody(2);
		}
		return dmg;
	}
	
	private void Jiggle(int stage)
	{
		/*
		GS_ChokeJiggler jig;
		if (stage < 0)	RemoveBehavior('GS_ChokeJiggler');
		else
		{
			jig = GS_ChokeJiggler(AddBehavior('GS_ChokeJiggler'));
			
		}
		*/
	}
	
	override String GetObituary(Actor s, Actor i, Name mod, bool pa)
	{
		if (mod == 'Melee')
		{
			static const string ob[] =
			{
				"Choke chose %o for snack time.",
				"%o was yummy yummy yummy. Now Choke's got food in his tummy",
				"Choke signed up for a bacon tournament and was pleased %o was the bacon.",
				"%o couldn't see the blur that was Choke before being treated like steak."
			};
			return ob[random(0, ob.Size()-1)];
		}
		static const string ob[] =
		{
			"Choke made %o see lots and lots of red.",
			"%o learned the hard way: Choke's no joke with his gory balls.",
			"%o thought it was all fun and games until Choke's goreball blew 'em up.",
			"Choke's gore balls sure fooled %o into thinking they weren't a threat."
		};
		return ob[random(0, ob.Size()-1)];
	}
	
	enum EGS_ChokeMode
	{
		PR_RANGE = 0,
		PR_MELEE,
		
		PR_MAX = PR_MELEE
	};
	private int pref, stimer;
	private void ChokeChase()
	{
		if (bKILLED)	return;
		if (--stimer < 1)
		{
			
			stimer = 35 * random[rng](5, 20);
			pref = (pref + 1) % PR_MAX;
		}
		Jiggle(0);
		if (pref == PR_MELEE)
		{
			A_Chase("Melee", null);
		}
		else
		{
			A_Chase();
		}
	}
	
	private void Bite()
	{
		A_StartSound("Choke/Melee",7,CHANF_OVERLAP);
		A_CustomMeleeAttack(10, "", "", "Melee");
	}
	private void ChokeDeath()
	{
		Jiggle(0);
		A_Scream();
		Fall();
	}
	private void ChokeBoom(bool big = false)
	{
		if (big)
		{
			int rng = random[rnd](7,10);
			for (int i = 0; i < rng; i++)
			{
				let ex = GhoulDeathExplo(Spawn('GhoulDeathExplo', pos + (0,0,height * 0.75), ALLOW_REPLACE));
				if (ex)
				{
					ex.big = true;
					ex.A_SetTranslation('GRed');
					if (i > 2)
						ex.silent = true;
				}
			}
		}
		else
		{
			Vector3 ps = Vec3Angle(frandom(0,radius * 2.0),random(0,359),frandom(height * 0.5, height * 2.5));
			let ex = GhoulDeathExplo(Spawn('GhoulDeathExplo', ps, ALLOW_REPLACE));
			if (ex)
			{
				ex.A_Face(self, 0, 0);
				ex.angle += 180;
				ex.pitch = -pitch;
				ex.A_SetTranslation('GRed');
				if (random[rng](0,1))
					ex.silent = true;
			}
		}
	}
}

class GS_ChokeBall : GS_Missile abstract
{
	Default
	{
		+EXTREMEDEATH
		+BRIGHT
		DamageType "Choke";
		DeathSound "Choke/BallImpact";
		Translation "0:255=%[0,0,0]:[1,0,0]";
		Species "Choke";
	}
	States
	{
	Spawn:
		X20A ABCD 3;
		Loop;
	Death:
		X221 F 0; // In the event it jumps straight to death.
		X221 FGHIJKL 3 A_Stop();
		---- A 1 A_FadeOut();
		Wait;
	}
}

class GS_ChokeBallLil : GS_ChokeBall
{
	Default
	{
		Speed 30;
		Damage 5;
		Scale 0.4;
	}
}

class GS_ChokeBallMed : GS_ChokeBall
{
	Default
	{
		Speed 20;
		Damage 15;
		Scale 0.75;
	}
}

class GS_ChokeJiggler : Behavior
{
	const moff = 10.0;
	const delup = 1.0 / 70.0;	
	const deldn = 1.0 / 35.0;
	private Vector2 ofs, prev;
	private double amp, step, goal, cur;
	private bool endme;
		
	private double Lerp (double x, double y, double a) 
	{	return x * (1.0 - a) + y * a;	}
	
	override void Initialize()
	{
		Super.Initialize();
		if (!Owner || Owner.bKILLED)	{	Destroy();	return;		}
		cur = goal;
		goal = moff;
		step = delup;
	}
	
	override void Reinitialize()
	{
		Super.Reinitialize();
		if (!Owner || Owner.bKILLED)	{	Destroy();	return;		}
		cur = goal;
		goal = 0;
		step = deldn;
		endme = true;
	}
	
	override void Tick()
	{
		if (bDESTROYED) return;
		if (!Owner || Owner.bKILLED)	{	Destroy(); return;	}
		
		
		Owner.SpriteOffset -= ofs;
		if (amp != goal)
		{
			amp = Lerp(cur, goal, step);
			if (abs(amp - goal) <= step)
			{
				if (endme)	{ Destroy();	return; }
				amp = goal;
			}
			/*
			else amp += step * (goal < amp) ? -1.0 : 1.0;
			*/
		}
		double ang = frandom[rng](0.0, 359.9);
		ofs = (cos(ang) * amp, -sin(ang) * amp);
		Owner.SpriteOffset += ofs;
	}
	override void OnDestroy()
	{
		if (Owner && Owner.bKILLED)
			Owner.SpriteOffset -= ofs;
		Super.OnDestroy();
	}
}