/*==============================================================================
	Creeper
	
An abandoned baby left floating down a river in a crib, he had no one to tend to
him. The Yurei, who felt pity for him, didn't have any way to care for him except
to feed him souls, and transformed him into a monster over time.

Now he stalks the forest as a semi-translucent monster, crawling quietly with
his hands while emitting barely audible whispers that, if potential victims are
careful enough to listen for, may help them avoid an untimely demise. However,
he also tends to throw curse balls which slow enemies, but in turn gives away his
position.

Upon finding a victim and closing in, it jumps up and scares the soul out of all
beings, bypassing all physical defenses and killing them almost instantly. It can
also move through walls. Whenever it's attacked, it'll quickly retreat a short
distance and try again.

The only upside is, he's the easiest ghoul to kill.

Recommended Weapon: Rocket Launcher or Shotgun
==============================================================================*/

class GS_Creeper : GS_GhoulBase
{
	const ChanVoice = 400;
	Default
	{
		GS_GhoulBase.PainDelay 5;
		Health 400;
		Height 16;
		Radius 13;
		xscale 0.8;
		yscale 0.1;
		Speed 16;
		Alpha 0.4;
		BloodColor "White";
		-DONTTHRUST
		+NOCLIP
		+NOEXTREMEDEATH
		+NODAMAGETHRUST
		+FORCERADIUSDMG
		MaxSlopeSteepness 0;
		Tag "Creeper";
		Species "GS_Creeper";
		SeeSound "GCreeper/Taunt";
	//	ActiveSound "GCreeper/Chase";
		PainSound "GCreeper/Pain";
		DeathSound "GCreeper/Death";
		
		
		DamageType "CreeperBoo";
		/*
		DamageFactor "Sjas", 0.6;
		DamageFactor "Jitter", 0.2;
		*/
	}
	
	override String GetObituary(Actor v, Actor i, Name mod, bool pa)
	{
		if (v is 'GS_Jitterskull')
		{
			static const string ob[] =
			{
				"%o's physical might couldn't save him from Creeper's power of slurp",
				"%o should've known better than to try eating haunted kids.",
				"%o diarrhea'd his flesh lunches out when scared crapless by a Creeper.",
				"%o now hates creepy kids. Damn whipper snappers are always trouble!",
				"%o's now filing a complaint with the Yurei about Creeper's OP bullshit."
			};
			return ob[random(0, ob.Size() - 1)];
		}
		else if (v is 'GS_Sjas')
		{
			static const string ob[] =
			{
				"Creeper clowned on %o with his far more frightening visage.",
				"The Creeper Scream Police arrived and forced %o to shut the Hell up.",
				"Creeper somehow managed to out-scream %o to death. Again.",
				"%o would've become King Screamer if it weren't for that meddlesome Creeper!",
				"Creeper turned %o into a joke by posting his screaming corpse on Ghoulstagram."
			};
			return ob[random(0, ob.Size() - 1)];
		}
		else if (v is 'GS_Choke')
		{
			static const string ob[] =
			{
				"%o's only good eye shot out of his skull when spooked by a Creeper",
				"%o's body and meals reacted comically and explosively when a Creeper punked him.",
				"Creeper grew tired of cleaning up %o's chonky messes.",
				"Creeper bitch slap't %o back to the Yurei for a therapy session.",
				"%o mistakenly let Creeper get under his skin with many creepy crawly feelings. Ick."
			};
			return ob[random(0, ob.Size() - 1)];
		}
		else if (v is 'GS_Frostbite')
		{
			static const string ob[] =
			{
				"Creeper proved %o's element of frost can't match that of spirit",
				"%o became Creeper's frosted blueberry icy malt.",
				"Creeper turned %o into the sweet treat that can beat hot sunny days",
				"Creeper was fed up with %o trying to recreate Freezeezy Peak via frost breath",
				"Creeper fed %o a ghost mint to fix his smelly frost breath. Results were head-shattering!"
			};
			return ob[random(0, ob.Size() - 1)];
		}
		static const string ob[] =
		{
			"%o WAAAAHAHAHAHARG'd from the Creeper's jumpscare",
			"Creeper finds %o falling out of their chair the funniest thing ever",
			"%o looked for the green creepers instead of the gray one nomming their soul",
			"%o shot out of his pants with a Wilhelm scream thanks to a Creeper.",
			"%o was GOTCHA!'d by a Creeper",
			"%o was drawn to a Creeper like a siren song and lost their soul",
			"A creeper PEEKABOO!'d poor %o's pants brown",
			"%o was surprise French kiss'd by a lonely Creeper. <3",
			"%o stepped into the wrong haunted house owned by Creeper",
			"%o now has yellow stains in their pants due to a Creeper"
		};
		return ob[random(0, ob.Size() - 1)];
	}
	
	override void Tick()
	{
		if (IsFrozen())	return;
		Super.Tick();
		if (bKILLED)	return;
		if (GotDelay > 0)	GotDelay--;
		if (BallDelay > 0)	BallDelay--;
	}
	
	override int DamageMobj(Actor i, Actor s, int damage, Name mod, int flags, double angle)
	{
		int dmg = Actor.DamageMobj(i, s, damage, mod, flags, angle);
		
		if (bKILLED || damage < 1)	return dmg;
		if (!bNOPAIN && !(flags & DMG_NO_PAIN) && (!i || !i.bPAINLESS))
		{
			if ((i && i.bFORCEPAIN) || (s && s.bFORCEPAIN) || (CurDmg + dmg >= DmgThreshold))
			{
				CurDmg = 0;
				let st = ResolveState("Pain");
				if (st) SetState(st);				
			}
		}
		if (dmg > 0)
			HandlePainSound(i, s, damage, mod, flags);
		return dmg;
	}
	
	private int GotDelay;
	void GotEm()
	{
		if (GotDelay > 0)	return;
		GotDelay = 35 * 4;
		A_StartSound("GCreeper/Gotcha", ChanVoice + 2);
	}
	// Take no indirect damage from other creepers
	override int TakeSpecialDamage(Actor i, Actor s, int damage, Name dtype)
	{
		if (s && s != self && s.GetClass() == GetClass())
			if (dtype != "Melee")
				return 0;
		return Super.TakeSpecialDamage(i, s, damage, dtype);
	}
	// Deals more damage to non-players (called by the popup)
	override int DoSpecialDamage(Actor target, int damage, Name dtype)
	{
		if (!(target is 'PlayerPawn') && dtype == 'CreeperBoo')
			damage *= 20;
			
		return Super.DoSpecialDamage(target, damage, dtype);
	}
	
	private void SetFear(bool on)
	{
		bNOFEAR = !on;
		bFRIGHTENED = on;
	}
	
	private void Peekaboo(Actor mo, bool noise = true, bool heal = true)
	{
		if (!mo || mo == self || bKILLED)
			return;
			
		let pop = GS_CreeperPopup(Spawn("GS_CreeperPopup", mo.pos, ALLOW_REPLACE));
		if (pop)
		{
			pop.target = self;
			pop.tracer = mo;
			pop.primary = (mo == target);
			pop.heal = heal;
			pop.noise = noise;
		}
	}
	
	private void Attack(bool mel = false)
	{
		if (mel)
		{
			if (target)
			{	
				/*
				if (target is 'PlayerPawn' || target.bNODAMAGE)
				{
					if (target.bINVULNERABLE || target.bNODAMAGE ||
						(target.player && target.player.cheats & (CF_GODMODE|CF_GODMODE2)))
					{	// Slap 'em back and retreat.
						A_CustomMeleeAttack(255);
						SetState(ResolveState("Pain"));
						return;
					}
				}
				*/
				Peekaboo(target, true);
				let it = GS_Global.MakeBTIPos(pos, (128, 256));
				Actor mo;
				int count = 0;
				while (it.Next())
				{
					mo = it.thing;
					if (!mo || !mo.bSHOOTABLE || mo.bKILLED || (mo is 'GS_GhoulBase') || (master && master == mo) || (mo is 'PlayerPawn'))
						continue;
					Peekaboo(mo, (mo is 'PlayerPawn' || count < 4));
					count++;
				}
			}
		}
		else
		{
			let mo = Spawn("GS_Creeperball", Vec3Offset(0, 0, 10), ALLOW_REPLACE);
			if (mo)
			{
				mo.target = self;
				mo.tracer = target;
				mo.A_FaceTracer(0,0);
				mo.Vel3DFromAngle(mo.Speed, mo.Angle, mo.Pitch);
				if (target is 'PlayerPawn')
				{
					mo.VelIntercept(target, mo.speed);
					mo.bSEEKERMISSILE = false;
				}
				else
					mo.bSEEKERMISSILE = true;
			}
		}
	}
	
	private void CreeperPain()
	{
		bNOPAIN = true;
		A_StopSounds(ChanVoice, ChanVoice+1);
		SetFear(true);
	//	SetFlashTimer(18);
	//	DamageFlash(true);
	//	S_StartSoundAt(pos, "Ghoul/Damaged", 5);
	}
	
	private void CreeperBoom()
	{
		if (bKILLED)
			A_FadeOut(0.01, 0);
		bool big = (alpha <= 0.0);
		if (big)
		{
			int rng = random[rnd](7,10);
			for (int i = 0; i < rng; i++)
			{
				let ex = GhoulDeathExplo(Spawn('GhoulDeathExplo', pos + (0,0,height * 0.75), ALLOW_REPLACE));
				if (ex)
				{
					ex.A_SetTranslation('GDamage1');
					ex.big = true;
					if (i > 2)
						ex.silent = true;
				}
			}
		}
		else
		{
			Vector3 ps = Vec3Angle(frandom(0,radius * 2.0),random(0,359),frandom(height * 0.5, height * 2.5));
			let ex = GhoulDeathExplo(Spawn('GhoulDeathExplo', ps, ALLOW_REPLACE));
			if (ex)
			{
				ex.A_Face(self, 0, 0);
				ex.angle += 180;
				ex.pitch = -pitch;
				ex.A_SetTranslation('GDamage1');
				if (random[rng](0,1))
					ex.silent = true;
			}
		}
		if (alpha <= 0.0)
			Destroy();
		else
			A_Wander();
	}

	private bool CheckTargetAim(bool defret = false)
	{
		if (Target is 'PlayerPawn')
		{
			let tr = new('GS_CreeperTrace');
			tr.to = self;
			tr.from = target;
			Vector3 dir;
			{
				double cpit = cos(Target.pitch);
				double ang = Target.angle;
				dir = (cos(ang) * cpit, sin(ang) * cpit, -sin(target.pitch));
			}
			Vector3 start = Target.Vec3Offset(0,0,Target.Height * 0.75);
			if (target.Player)	
			{
				start.Z = target.Player.viewZ;
				let vp = target.ViewPos;
				if (vp)
				{
					Vector3 ofs = vp.Offset;
					int flags = vp.Flags;
					if (flags & VPSF_ABSOLUTEPOS)
						start = ofs;
					else if (flags & VPSF_ABSOLUTEOFFSET)
						start = level.Vec3Offset(start, ofs);
					else
					{
						Quat rel = Quat.FromAngles(Target.Angle, Target.Pitch, Target.Roll);
						Vector3 next = rel * ofs;
						start = level.Vec3Offset(start, next);
					}
				}
				else start = Target.Vec2OffsetZ(0,0, target.player.ViewZ);
			}
			
			tr.Trace(start, Target.CurSector, dir, 2048, 0, ignore: Target);
			let res = tr.Results;
			return (res.HitType == TRACE_HitActor && res.HitActor == self);
		}
		else if (Target.bISMONSTER)
		{
		//	bool sn = (target is 'PlayerPawn' || target.target == self);
		//	return (sn && AbsAngle(Target.angle, Target.AngleTo(self)) < 10);
			return true;
		}
		return defret;
	}
	private int BallDelay;
	private bool Seen;
	private Actor OldTarget;
	private void CreeperChase(bool mel = true, bool misl = true)
	{
		if (bKILLED)	return;
		A_StartSoundIfNotSame("GCreeper/Chase","GCreeper/Chase", 398, CHANF_LOOP);
		if (Target && !Target.bKILLED)
		{
			if (misl)
			{
				if (Target != OldTarget)
				{
					Seen = false;
					OldTarget = Target;
				}
				
				if (!Seen)
					Seen = CheckTargetAim();
				
				if (Seen && BallDelay < 1)
				{
					BallDelay = random[rng](15,25);
					if (misl && CheckSight(target, SF_IGNOREVISIBILITY|SF_IGNOREWATERBOUNDARY))
						Attack(false);
				}
			}
			A_FaceTarget(0);
			Vector2 v = Vec2Angle(speed, (bFRIGHTENED ? angle + 180 : angle));
			if (pos.z <= floorz && vel.z ~== 0.0)
				TryMove(v, (bDROPOFF || bNOCLIP));
			if (mel && CheckMeleeRange())
			{
				SetState(ResolveState("Melee"));
				return;
			}
		}
		else
		{
			OldTarget = Target;
			if (mel)	A_Chase(flags: CHF_DONTMOVE|CHF_DONTTURN|CHF_NODIRECTIONTURN);
			else		A_Chase(null, flags: CHF_DONTMOVE|CHF_DONTTURN|CHF_NODIRECTIONTURN);
		}
		
	}
	
	States
	{
	Spawn:
		G001 A 15 GhoulLook();
		Loop;
	See:
		G001 A 0 { SetFear(false); PlaySeeSound(); }
		
	Chasing:
		---- A 0 A_StartSound("GCreeper/Chase", 398, CHANF_LOOP);
	ChaseLoop:
		G001 AAAABBBB 2 CreeperChase();
		Loop;
	Melee:
		G001 A 0 
		{
			Attack(true);
			CreeperPain();
		}
		G001 ABABABABABABABABAB 1 bright CreeperChase(false);
		Goto PainCont;
	Pain:
		G001 A 0 CreeperPain();
		G001 ABABAB 1 bright CreeperChase(false);
		G001 ABABABABABAB 1 bright CreeperChase();
	PainCont:
		G001 E 0 { bNOPAIN = false; }
		G001 ABABABABABAB 2 CreeperChase();
		G001 ABABABABABAB 3 CreeperChase();
		G001 A 0 SetFear(false);
		Goto Chasing;
	Death:
		G001 D 0 
		{
			bNOCLIP = false;
			bTHRUACTORS = true;
			Speed = Default.Speed * 0.25;
			A_Scream();
			Fall();
			A_FadeIn(1.0, FTF_CLAMP);
			A_SetScale(0.06);
		}
		---- A 1 Bright CreeperBoom();
		Wait;
	}
}

//------------------------------------------------------------------------------	
class GS_CreeperTrace : LineTracer
{
	Actor from, to;
	override ETraceStatus TraceCallback()
	{
		Switch (Results.HitType)
		{
			Case TRACE_HitActor:
			{
				let mo = Results.HitActor;
				return (mo == to) ? TRACE_Stop : TRACE_Skip;
			}
			Case TRACE_HitFloor:
			Case TRACE_HitCeiling:
			Case TRACE_HitNone:
				return TRACE_Stop;
			
			Case TRACE_HitWall:
			{
				if (Results.Tier == TIER_Upper || Results.Tier == TIER_Lower) 
					return TRACE_Stop;
			
				let hf = Results.HitLine.Flags;
				if (hf & (Line.ML_BLOCKEVERYTHING | Line.ML_BLOCKSIGHT))
					return TRACE_Stop;
				
				if ((hf & Line.ML_BLOCKING) && !(hf & Line.ML_TWOSIDED))
					return TRACE_Stop;
			}
		}
		return TRACE_Skip;
	}
}
//------------------------------------------------------------------------------	

class GS_CreeperPopup : Actor
{
	const maxdiv = 4;
	const _height = 56;
	const hdiv = _height / maxdiv;
	bool primary, heal, noise;
	Default
	{
		Projectile;
		+NOINTERACTION
		+BRIGHT
		+PIERCEARMOR
		+FORCEYBILLBOARD
		+NOEXTREMEDEATH
		Radius 16;
		Height _height;
		Scale 0.05;
		RenderStyle "Translucent";
		DamageType "CreeperBoo";
	}
	
	private int count;
	private bool isalive, killcheck;
	
	private void BOO()
	{
		if (!Tracer)	return;
		isalive = (primary && !Tracer.bKILLED);
		int dmg = Tracer.DamageMobj(self, target, 50, DamageType, DMG_THRUSTLESS);
		if (heal && dmg > 0 && Target && !Target.bKILLED)	Target.GiveBody(10);
		killcheck = (isalive && Tracer.bKILLED);
	}
	
	private void Popup()
	{
		if (Tracer)
		{
			Vector3 v;
			v.XY = Tracer.Vec2Angle(10, Tracer.Angle);
			v.Z = Tracer.Pos.Z - height + Clamp(hdiv * count, 0, height);
			SetOrigin(v, (count > 0));
		}
		
		if (!Target || Target.bKILLED)
			return;
		
		Switch (count++)
		{
			Case 0:	
			{
				if (!(Tracer is 'PlayerPawn'))
					BOO();
				if (noise) A_StartSound("GCreeper/Attack", 5);	
				break;
			}
			Case 6:
			{
				if (Tracer is 'PlayerPawn')
					BOO();
				Tracer.A_GiveInventory("GS_CreeperImmunity",1);
				break;
			}
			Case 12:
			{
				if (killcheck && target && tracer)
				{
					let cr = GS_Creeper(Target);
					if (cr && !cr.bKILLED)	cr.GotEm();
				}
				break;
			}
		}
	}
	/*
	override int DoSpecialDamage(Actor trg, int damage, Name damagetype)
	{
		return (target) ? target.DoSpecialDamage(trg, damage, damagetype) : damage;
	}
	*/
	States
	{
	Spawn:
		G001 CCCCCCCCC 1 Popup();
	Fading:
		---- A 1 
		{	
			Popup();
			A_FadeOut();
		}
		Wait;
	}
}

class GS_CreeperImmunity : PowerProtection
{
	Default
	{
		Powerup.Duration 15;
		DamageFactor "CreeperBoo", 0.0;
	}
}

const CreeperSlowDuration = 35;
class GS_CreeperSlow : PowerSpeed
{
	const MaxTime = 35 * 10;
	Default
	{
		Speed 1.0;
		Powerup.Duration CreeperSlowDuration;
		+INVENTORY.ADDITIVETIME
		Inventory.InterhubAmount 0;
	}
	
	override void PreTravelled()
	{
		Amount = 1;
	}
	
	override bool IsBlinking()	{	return true;	} // disables color screen
	
	private double RealSpeed, CurSpeed, Cap;
	override void InitEffect()
	{
		Super.InitEffect();
		if (!Owner)	return;
		Cap = (Owner is 'PlayerPawn') ? 0.5 : 0.25;
		RealSpeed = Owner.Speed;
	}
	
	override void DoEffect()
	{
		if (!Owner)	
		{	Destroy(); return; }
		
		if (Owner.bINVULNERABLE)
		{
			EffectTics = 1;
			Super.DoEffect();
			return;
		}
		
		if (Owner.Speed != CurSpeed)
			RealSpeed = Owner.Speed; // The owner performed a speed change
		
		Super.DoEffect();
		if (EffectTics > MaxTime)
			EffectTics = MaxTime;
		else if (EffectTics < 1)
			return;
		
		Amount = int(ceil(double(EffectTics * 10.0) / 35.0));
		
		CurSpeed = Max(Cap, (RealSpeed - (0.01 * Amount)));
		Owner.Speed = CurSpeed;
	}
	/*
	private bool checked;
	override double GetSpeedFactor()
	{
		Speed = Max(Cap, (Default.Speed - (0.01 * double(Amount))));
		return Speed;
	}
	*/
	override void EndEffect()
	{
		if (Owner)
			Owner.Speed = RealSpeed;
		Super.EndEffect();
	}
	
}

class GS_CreeperBall : GS_Missile
{
	int DmgMin, DmgMax;
	Property Dmg: DmgMin, DmgMax;
	Default
	{
		GS_CreeperBall.Dmg 2, 4;
		Projectile;
		+THRUSPECIES
		+MTHRUSPECIES
		+BRIGHT
		speed 42;
		damagefunction (0); // Not used on purpose.
		height 8;
		radius 6;
		scale 0.6;
		renderstyle "Add";
		Species "GS_Creeper";
		seesound "GCreeper/Curse";
		deathsound "GCreeper/Cursed";
	//	obituary "%o was unlucky enough to be slow-deathed by a Creeper's balls." ;
	}
	
	override int SpecialMissileHit(Actor mo)
	{
		if (!mo)	return 1;
		if (mo == target || (bMTHRUSPECIES && mo.species == species))	
		{
			if (mo != tracer)
				return 1;
		}
		if ((mo is 'PlayerPawn' || mo.bISMONSTER) && !mo.bKILLED)
		{
			if ((!mo.bREFLECTIVE || bDONTREFLECT) && !mo.bINVULNERABLE)
			{
				let inv = 	GS_CreeperSlow(mo.FindInventory("GS_CreeperSlow"));
				if (inv)	inv.EffectTics += CreeperSlowDuration;
				else		mo.A_GiveInventory("GS_CreeperSlow",1);
			}
			if (mo.bFLOAT)
				mo.DamageMobj(self, target, random[rng](DmgMin,DmgMax), Damagetype);
			else
			{
				bool bud = mo.bBUDDHA;
				mo.bBUDDHA = true;
				mo.DamageMobj(self, target, random[rng](DmgMin,DmgMax), Damagetype);
				mo.bBUDDHA = bud;
			}
		}
		
		return -1;
	}
	
	override int DoSpecialDamage(Actor trg, int dmg, Name type)
	{
		if (trg)
		{
			if (trg is 'GS_GhoulBase')
				if (!trg.bBOSS)
					dmg *= 10;
			else if (trg.bISMONSTER)
				dmg *= 10;
		}
		return dmg;
	}
	
	private void DoSeek()
	{
		if (Tracer && !(tracer is "PlayerPawn"))
			A_SeekerMissile(20, 20, SMF_PRECISE);
	}
	
	States
	{
	Spawn:
		X20A ABCD 3 DoSeek();
		Loop;
	Death:
		X20A EFGHIJ 3 A_SetTranslucent(1.0, 1);
		Stop;
	}
}

